[project]
name = "ce290i-microservices"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faker>=37.12.0",
    "fastapi[standard]>=0.120.4",
    "streamlit>=1.51.0",
]
